debug: false
server:
  host: 0.0.0.0
  port: 80
db:
  host: redis
  port: 6379
  index: 0
  test_index: 1
  key-prefix: visit-counter
  keys:
    visits: visits
    test_key: test_visits
log:
  path: '/var/log/vcounter.web.log'
  rotation:
    after: 1 day
    retention: 7 days
