debug: true
server:
  host: localhost
  port: 8000
db:
  host: localhost
  port: 6379
  index: 0
  test_index: 1
  key-prefix: visit-counter
  keys:
    visits: visits
    test_key: test_visits
log:
  path: '/absolute/path/to/web.log'
  rotation:
    after: 1 day
    retention: 7 days
